#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-release
Version  : 2.5.3
Release  : 1
URL      : https://github.com/apache/maven-release/archive/maven-release-2.5.3.tar.gz
Source0  : https://github.com/apache/maven-release/archive/maven-release-2.5.3.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.3/maven-release-plugin-2.5.3.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.3/maven-release-plugin-2.5.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
Deploying web site
-------------------
see http://maven.apache.org/developers/website/deploy-component-reference-documentation.html

%prep

%build

%install

%files
%defattr(-,root,root,-)
